events {
    worker_connections 1024;
}

http {
    server {
        listen 80;
        client_max_body_size 50M;
        # When you get your custom domain, you can update this:
        # server_name api.optichash.com;

        location / {
            # Route all traffic directly to the internal Java Gateway container
            proxy_pass http://gateway_service:8080;
            
            # Preserve the original client headers
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }
}